name = "Create Game Night"
author = "Svemat01"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "20676d35a37f7b89043e3bee47f8097b9bf09c99cd27a5e7d5b7ebeb6daa86c1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.169"
